[package]
name = "drumz"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.61"
cpal = "0.13.5"
fundsp = "0.8.0"
